### ISSUE TITLE
When audio is null, it crashes with Null Pointer Exception

### ISSUE THREAD

**Issue by ahmetturk** [dburckh/bitmap2video#10]
```
muxer.mux(bitmapList)
```

I don't give audioTrack, so its default is null. It makes audioExtractor null. When muxAudioFrames() function is called, it crashes. Can you add an if check when calling muxAudioFrames()? Thank you.

```
if (audioTrack != null) {
    frameBuilder.muxAudioFrames()
}
```

**Comment by pingrishabh** [comment]
+1

**Comment by KiwanPark** [comment]
+1
